### PR TITLE
make a libdeflate-sys sub-crate

### PR DESCRIPTION
**Pull request by pmarks**

### CODE REVIEW

**Comment by pmarks** [comment]
@adamkewley a PR to add a -sys crate.

**Comment by pmarks** [comment]
fixed in #4

**Comment by adamkewley** [comment]
Looks great. 

As always, thank you for putting the time in to do this. I'll get this merged and published so that you can just pull `libdeflate-sys` and not have to take my wrapper along for the ride.

**Comment by adamkewley** [comment]
Ok, after a little drama from `cargo publish`, I've managed to put a release (0.5.0) of `libdeflate-sys` up:

https://crates.io/crates/libdeflate-sys

And also updated the bindings version accordingly, etc:

https://crates.io/crates/libdeflater

**Pull request merged**
