### PR TITLE
Implemented std::error::Error for DecompressionError

### PR DESCRIPTION
**Pull request by adamkewley**
Relates to: https://github.com/adamkewley/libdeflater/issues/7

@joshtriplett noticed that `DecompressionError` does not implement `std::error::Error`. Big oversight by me. This PR adds that functionality.

@joshtriplett , if you're around, could you quickly check the diff for this? I'll go ahead and merge it but the error messages might benefit from a touch-up in a later commit. I figure it's best to ship *something* right now that fixes this oversight--after all, it's a non-breaking addition--and I'm happy to clean up the error messages later.

### CODE REVIEW

**Comment by joshtriplett** [comment]
source shouldn't return self; source is for a different error that caused this one. Leave that function out entirely.

Also, the display strings don't conventionally include the type variant as a prefix; you can drop that bit.

**Comment by adamkewley** [comment]
@joshtriplett thanks for reading this - sorry for the hassle

I've removed those prefixes and the needless `source` function (sorry: haven't implemented these interfaces before)

**Comment by adamkewley** [comment]
I'll get this merged and roll it out with the next path release, thanks again @joshtriplett

**Comment by adamkewley** [comment]
Published in 0.7.1: https://crates.io/crates/libdeflater

**Pull request merged**
