### PR TITLE
Update libdeflate: fix freestanding + -Zbuild-std

### PR DESCRIPTION
**Pull request by RReverser**
Fixes usage of `freestanding` feature in combination with `-Zbuild-std` builds (or when linking with any other library that also shims global `mem*` helpers).

See https://github.com/ebiggers/libdeflate/issues/107 for details.

@adamkewley Once merged, could you please make another patch release for libdeflate-sys & libdeflater?

### CODE REVIEW

**Comment by adamkewley** [comment]
@RReverser thanks for looking into this. I was keeping an eye on the upstream PR but i've been very busy recently.

I've checked your commit, rebuilt + tested it, etc. and it all seems fine. I will go ahead and merge it, then publish a new version of `libdeflater`

**Comment by RReverser** [comment]
Awesome, thanks!

**Comment by adamkewley** [comment]
Merged + published as 0.7.0: https://crates.io/crates/libdeflater

**Comment by RReverser** [comment]
Nice, thanks! I thought 0.6.1 should be sufficient, but I guess with all the other upstream changes it's better to be on the safe side.

**Pull request merged**
